name: otel-collector
services:
    opentelemetry-collector:
        ports:
            - 4317:4317
            - 4318:4318
        volumes:
            - $(pwd)/collector-config.yaml:/etc/otelcol/config.yaml
        image: otel/opentelemetry-collector